### ISSUE TITLE
Feedback from JSON backend change demo

### ISSUE THREAD

**Issue by panges2** [filecoin-project/filplus-registry#23]
Overall great job! We have come a long way from planning everything till now. we're almost at the finish line and just have to get the following discussion topics out of the way. Feel free to make these into work item tasks in this board

### Small UX things
- Need to test functionality of searching for a certain applcation by number/name
- Default should be table instead of grid
- Should be able to filter by state
    - by default (for notaries and rkh) should filter out everything except: submitted, ready to sign, start sign datacap
    - Should still be able to see things that are not active if they want to

### Status and Labels
We need to finalize the names for labels and have a state field in the JSON file. In my opinion we should not change the label names from what we currently have here: https://medium.com/p/ae2691c78702/edit. Updating the names will only cause more confusion with existing clients. We should only change `validated` to `submitted`

The happy flow should be:
- client applies, and acknowledges they have applied by changing state to `submitted` (can be done by default if applied through issue/ filplus.storage). `submitted` becomes the beginning state. Application should only show in front end to be triggered if state is `submitted`
- Gov team sees the application on frontend and triggers the application this turns `isTriggered` field in the JSON file to be `true` and changes the state to become `ready to sign`. The front end should update appropriately and it should be seen by notaries. `isActive` is also set to true
- after one notary signs it, the status is changed to `start sign datacap` and the front end changes appropriately. If the signing does not land on chain, the status change should not happen.
- Another notary (cannot be the same) has to sign it, datacap is allocated and the status changes to `granted`. `isActive` is set to false
- When all the tranches are given to the client, they have completed their application and the status is changed to `total datacap reached`. `isActive` is set to false

When there is an unhappy flow these labels will be used:
- `governance review needed` should be if they try to edit anything/ there is a weird state that is invalid according to the validation script
- `error` is if there is something wrong with the system.

### Validation script
Validation script plays a crucial role in this flow as it should handle all unhappy flows. I describe what I think should be the behavior of the validation script here: https://hackmd.io/yKk-57JhRQS2u_DMjyRnVA#Validation-script @Esraa pls pls pls read through this and make sure validation script acts according to this. If there is stuff in there your not sure about/ edgecases ping me. Here are some flows, I think we should be able to demo before launch:
- Client tries to change something before it is triggered -> nothing should happen, but the validation script should still run not allowing them to merge + it should not show on the front end
- Client changes the state to submited, then it shows on front end and gov team triggers it. Changing the status to `ready to sign`
- Client tries to edit stuff after it is triggered -> validation script should see this and change the state to `governance review needed`
    - client tries to change `governance review needed` back to `ready to sign` -> validation script sees this and changes it back to `governance review needed`
    - gov team changes the state back to `ready to sign` -> validation script should allow this
- A notary signs the application and changes the state to `start sign datacap`
- another notary comes in and edits the file to manually look like they signed, for the CID field, they put a random CID -> validation script should detect this as the CID in the JSON file does not correspond to the correct CID. State should be changed to `governance review needed`
- the state is fixed and this time a notary actually signs through the front end so everything is correct. allocation is granted and state is turned to `granted`
- A notary tries to manually start a new `allocationTranche` object -> validation script should detect this because client is not <25% datacap and change the state to `governance review needed`
    - the state is fixed and then client uses up 75% datacap. If a notary then tries to do the same thing -> validation script will check that client has <25% and claim its valid  

### The JSON structure itself
We need to finalize the JSON structure. I think it should look like something based of of this: https://filecoinproject.slack.com/archives/C016F8D7V09/p1694552284307949?thread_ts=1694528162.492339&cid=C016F8D7V09
so something like:

```
{
  "applicationVersion": 1,
  "dataCapApplicationType": "da | ldn-v3 | e-fil",
  "projectId": 1,
  "datacapApplicant": "",
  "applicationInfo": {
    "coreInformation": {
      "Data Owner Name": "",
      "Data Owner Country/Region": "",
      "Data Owner Industry": "",
      "Website": 0,
      "Social Media": {
        "handle": "",
        "type": "Slack | Twitter | Facebook"
      },
      "What is your role related to the dataset": "",
      "Total amount of DataCap being requested": {
        "amount": 0,
        "unit": "GiB | TiB | PiB"
      },
      "Expected size of single dataset (one copy)": {
        "amount": "",
        "unit": "GiB | TiB | PiB"
      },
      "Number of replicas to store (minimum 4)": 0,
      "Weekly allocation of DataCap requested": {
        "amount": "",
        "unit": "GiB | TiB | PiB"
      },
      ""On-chain address (Note that you will not be able to change this in the future and that you should have a unique address for each LDN application)": "",
      "Data Type of Application": "Slingshot | Public, Open Dataset (Research/Non-Profit) | Public, Open Commercial/Enterprise | Private Commercial/Enterprise | Private Non-Profit / Social impact",
      "Custom multisig": ""
    },
    "projectDetails": {
      "Share a brief history of your project and organization": "",
      "Is this project associated with other projects/ecosystem stakeholders?": true,
      "If answered yes, what are the other projects/ecosystem stakeholders": ""
    },
    "useCaseDetails": {
      "Describe the data being stored onto Filecoin": "",
      "Where was the data currently stored in this dataset sourced from": "AWS Cloud | Google Cloud | Azure Cloud | My Own Storage Infra | other",
      "If you answered 'Other' in the previous question, enter the details here": "",
      "How do you plan to prepare the dataset": "IPFS | Lotus | Singularity | Graphsplit | other/custom tool",
      "If you answered 'other/custom tool' in the previous question, enter the details here": "",
      "Please share a sample of the data (a link to a file, an image, a table, etc., are good ways to do this.)": "",
      "Confirm that this is a public dataset that can be retrieved by anyone on the network (i.e., no specific permissions or access rights are required to view the data)": true,
      "If you chose not to confirm, what was the reason": "",
      "What is the expected retrieval frequency for this data": "Daily | Weekly | Monthly | Yearly | Sporadic | Never",
      "For how long do you plan to keep this dataset stored on Filecoin": "Less than a year | 1 to 1.5 years | 1.5 to 2 years | 2 to 3 years | More than 3 years | Permanently"
    },
    "datacapAllocationPlan": {
      "In which geographies do you plan on making storage deals": [
        
      ],
      "How will you be distributing your data to storage providers": "",
      "How do you plan to choose storage providers": "",
      "If you answered 'Other' in the previous question, what is the tool or platform you plan to use": "",
      "Please list the provider IDs and location of the storage providers you will be working with. Note that it is a requirement to list a minimum of 5 unique provider IDs, and that your client address will be verified against this list in the future": [{"providerID": "", "location": "",  "SPOrg",""}],
      "How do you plan to make deals to your storage providers": "",
      "If you answered 'Others/custom tool' in the previous question, enter the details here": "",
      "Can you confirm that you will follow the Fil+ guideline (Data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap)": ""
    }
  },
  "applicationLifecycle": {
    "state": "submitted | ready to sign | start sign datacap | granted | total datacap reached | governance review needed | error", 
    "validatedTime": 0,
    "firstAllocationTime": 0,
    "isTrigered": false,
    "isActive": true,
    "timeOfNewState": 0
  },
  "dataCapAllocations": [
    {
      "dataCapTranche": {
        "trancheID": 0,
        "clientAddress": "f1...",
        "timeOfRequest": 0,
        "timeOfAllocation": 0,
        "notaryAddress": "",
        "allocationAmount": 0,
        "signers": [
          {
            "githubUsername:" "",
            "signingAddress": "",
            "timeOfSignature": 0,
            "messageCID": ""
          },
          {
            "githubUsername:" "",
            "signingAddress": "",
            "timeOfSignature": 0,
            "messageCID": ""
          }
        ],
        "pr": 0,
      }
    }
  ]
}
```
It's alot let me know if you have uestions here^

### Open source and document everything
This we can discuss nearer to launch/after launch

```[tasklist]
### Tasks
- [ ] functionality of searching for a certain applcation by number/name
- [ ] Default should be table instead of grid
- [ ] Should be able to filter by state: 
    - by default (for notaries and rkh) should filter out everything except: submitted, ready to sign, start sign datacap
     - Should still be able to see things that are not active if they want to
```

**Comment by jbesraa** [comment]
thanks @panges2 this all makes sense. we will convert things to smaller chunks and implement them. 
regarding failing scenarios that you wanna see in the next demo, do you any preferences for specific scenarios?

**Comment by clriesco** [comment]
Closed as completed
